### PR TITLE
Import some sound files from meditation app and refactor code.

### LINKED ISSUE #110: Maybe we can import some new sounds from meditation.
meditation has some new beautiful sounds, maybe we can import.

https://github.com/nyxkn/meditation/tree/main/assets

### PR DESCRIPTION
**Pull request by tumashu**
Import some sound files from meditiation app:

  https://github.com/nyxkn/meditation

and the sound files of meditiation are derived from:

- bell1: <https://freesound.org/people/LozKaye/sounds/94024/> (CC0)
- bell3: <https://soundbible.com/1690-Indian-Bell.html> (CC Sampling Plus 1.0)
- bell4: <https://freesound.org/people/fauxpress/sounds/42095/> (CC0)
- bell5: <https://freesound.org/people/ryancacophony/sounds/202017/> (CC0)
- bowl2: <https://freesound.org/people/juskiddink/sounds/122647/> (CC-BY 3.0)
- bowl3: <https://freesound.org/people/Garuda1982/sounds/116315/> (CC0)
- gong2: <https://freesound.org/people/nkuitse/sounds/18654/> (CC0)

### CODE REVIEW

**Comment by tumashu** [comment]
ping ：)

**Comment by tzugen** [comment]
Hi :)
Sorry there is always some weeks where I have time for the OSS projects and some where i dont :)

I would like to push to your branch, there should be a setting somewhere to allow maintainers of the app to modify your PR, can you activate it?

**Comment by tzugen** [comment]
I have installed it on my phone and will check it out during the next days.

**Comment by tumashu** [comment]
@tzugen Allow edits by maintainers has been activated

**Comment by tzugen** [comment]
On problem I found: 
When I installed this version it forgot which tone I had set before and became silent.
I had to repick it again. This should not happen, it will confuse the users.

**Comment by tzugen** [comment]
Its because you renamed the existing sounds.
Then you need to also take care to update the preference values of the users...

**Comment by tumashu** [comment]
@tzugen code deal with this issue seem to ugly, what about keep old sound files for 1-2 year, then remove?.

**Comment by tumashu** [comment]
i have found that keeping old file name as possible seem to more simper

**Comment by tumashu** [comment]
Updated, please try again.

**Comment by tzugen** [comment]
Ok, now its good!
Thank you:)

**Comment by tumashu** [comment]
ok, I have updated zh translation, suggest pull and release a new version

**Comment by tzugen** [comment]
I have submitted a new version to Play store but it has been rejected for a reason I dont understand. I just tried again now. It is often super random.

**Comment by tzugen** [comment]
Hi @tumashu

This email arrived. Can you have a look?
Dear Sir/Mdm,
I have been using Bodhi Timer for many years. Lately, I noticed that the singing bowl high sound became shortened. I uninstalled and reinstalled the app, and start bell was not working. I tried to uninstall and reinstall again for a couple of times but it did not work. Please kindly help. Thank you very much!

**Comment by tumashu** [comment]
singing bowl high sound became shortened? what does this mean？

**Comment by tumashu** [comment]
i have tested,  bowl.ogg is 12 second, no different

**Comment by tumashu** [comment]
If Use old Notification Method is enabled, i found sometimes sound will become shorter for stop play ogg.

**Pull request merged**
